// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBIpQi2O4bkOROyeJg-i6HfgOpZdf-Jq5I',
    appId: '1:675529152947:web:2274da4db606e20db613c6',
    messagingSenderId: '675529152947',
    projectId: 'gaugyam',
    authDomain: 'gaugyam.firebaseapp.com',
    storageBucket: 'gaugyam.firebasestorage.app',
    measurementId: 'G-LLT7XST91V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAWGtFUjQ_DsByh32lMVm6X7Jst-C_f3Nw',
    appId: '1:675529152947:android:8a00e18af5663feab613c6',
    messagingSenderId: '675529152947',
    projectId: 'gaugyam',
    storageBucket: 'gaugyam.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBnD0IRE-C8rYaOSiALUJxz1wf0iGJMEt8',
    appId: '1:675529152947:ios:8a916b77f6113804b613c6',
    messagingSenderId: '675529152947',
    projectId: 'gaugyam',
    storageBucket: 'gaugyam.firebasestorage.app',
    iosBundleId: 'com.gaugyam.gaugyam',
  );
}
